/**
 * Mock data for the Styrdokument showcase — shaped to the real `DocumentItem`
 * type so the actual `DocumentTable` renders unchanged. Nordviken framing.
 */
import type { DocumentItem } from '@/components/features/documents/document-table'

const TS = (s: string) => new Date(s).toISOString()

export const DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'Rutin för ansvarsfull alkoholservering',
    document_type: 'PROCEDURE',
    status: 'APPROVED',
    document_number: 'RUT-014',
    current_version_number: 3,
    review_date: '2026-09-01',
    created_at: TS('2025-02-10'),
    updated_at: TS('2026-03-02'),
    creator: {
      id: 'u-anna',
      name: 'Anna Lindqvist',
      email: 'anna@nordviken.se',
    },
  },
  {
    id: 'doc-2',
    title: 'Systematiskt arbetsmiljöarbete – policy',
    document_type: 'POLICY',
    status: 'APPROVED',
    document_number: 'POL-002',
    current_version_number: 5,
    review_date: '2026-06-15',
    created_at: TS('2024-11-01'),
    updated_at: TS('2026-02-18'),
    creator: {
      id: 'u-sofia',
      name: 'Sofia Karlsson',
      email: 'sofia@nordviken.se',
    },
  },
  {
    id: 'doc-3',
    title: 'Riskbedömning kök & servering 2026',
    document_type: 'RISK_ASSESSMENT',
    status: 'IN_REVIEW',
    document_number: 'RISK-021',
    current_version_number: 2,
    review_date: '2026-05-30',
    created_at: TS('2026-01-20'),
    updated_at: TS('2026-04-28'),
    creator: { id: 'u-erik', name: 'Erik Holm', email: 'erik@nordviken.se' },
  },
  {
    id: 'doc-4',
    title: 'Behandling av personuppgifter (GDPR)',
    document_type: 'POLICY',
    status: 'APPROVED',
    document_number: 'POL-008',
    current_version_number: 4,
    review_date: '2026-12-01',
    created_at: TS('2024-05-12'),
    updated_at: TS('2026-01-09'),
    creator: { id: 'u-johan', name: 'Johan Berg', email: 'johan@nordviken.se' },
  },
  {
    id: 'doc-5',
    title: 'Handlingsplan brandskydd',
    document_type: 'ACTION_PLAN',
    status: 'DRAFT',
    document_number: null,
    current_version_number: 1,
    review_date: null,
    created_at: TS('2026-04-15'),
    updated_at: TS('2026-04-15'),
    creator: { id: 'u-maria', name: 'Maria Ek', email: 'maria@nordviken.se' },
  },
  {
    id: 'doc-6',
    title: 'Egenkontroll livsmedel – instruktion',
    document_type: 'INSTRUCTION',
    status: 'APPROVED',
    document_number: 'INS-031',
    current_version_number: 2,
    review_date: '2026-08-20',
    created_at: TS('2025-06-03'),
    updated_at: TS('2026-02-25'),
    creator: {
      id: 'u-anna',
      name: 'Anna Lindqvist',
      email: 'anna@nordviken.se',
    },
  },
  {
    id: 'doc-7',
    title: 'Checklista öppning & stängning',
    document_type: 'CHECKLIST',
    status: 'APPROVED',
    document_number: 'CHK-005',
    current_version_number: 6,
    review_date: '2026-07-01',
    created_at: TS('2024-09-18'),
    updated_at: TS('2026-03-30'),
    creator: {
      id: 'u-sofia',
      name: 'Sofia Karlsson',
      email: 'sofia@nordviken.se',
    },
  },
]
