/**
 * Daily Vercel cron — triggers a production rebuild via Vercel Deploy Hook
 * so the static sitemap files in public/ (generated by scripts/generate-sitemaps.ts
 * during postbuild) get refreshed with new ACTIVE legal documents.
 *
 * Configured in vercel.json at "30 16 * * *" (16:30 UTC daily) — 30 min after
 * the sync-sfs cron at 16:00 UTC so all daily SFS ingestion has landed before
 * the rebuild captures it.
 *
 * Auth: Bearer ${CRON_SECRET}, mirroring app/api/cron/expire-trials/route.ts.
 *
 * Requires VERCEL_DEPLOY_HOOK_URL env var pointing at a Deploy Hook configured
 * in Vercel UI (Settings → Git → Deploy Hooks) against the main branch.
 */

import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'
export const maxDuration = 30

export async function GET(request: Request) {
  const authHeader = request.headers.get('authorization')
  const cronSecret = process.env.CRON_SECRET

  if (process.env.NODE_ENV === 'production' && cronSecret) {
    if (authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }
  }

  const hookUrl = process.env.VERCEL_DEPLOY_HOOK_URL
  if (!hookUrl) {
    console.error('[refresh-sitemap] VERCEL_DEPLOY_HOOK_URL is not set')
    return NextResponse.json(
      { error: 'VERCEL_DEPLOY_HOOK_URL missing' },
      { status: 500 }
    )
  }

  const res = await fetch(hookUrl, { method: 'POST' })

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    console.error(
      `[refresh-sitemap] deploy hook returned ${res.status}: ${body}`
    )
    return NextResponse.json(
      { error: 'Deploy hook failed', status: res.status },
      { status: 502 }
    )
  }

  console.log(`[refresh-sitemap] deploy hook fired (${res.status})`)
  return NextResponse.json({ ok: true, status: res.status })
}
