/**
 * Build-time generator for lib/agent/skills.generated.ts.
 *
 * Scans lib/agent/skills/ via the filesystem scanner (lib/agent/skill-fs.ts)
 * and inlines every skill's validated frontmatter + fully-assembled body into a
 * static TypeScript module. The runtime loader (lib/agent/skill-loader.ts)
 * imports that manifest instead of reading the filesystem at request time —
 * which removes the dynamic-path fs reads that made Turbopack/nft widen the
 * /api/chat trace to the whole repo (~16.5k files) and emit a build warning.
 *
 * Wired into `prebuild` (runs before `next build`); the output is also
 * committed so dev / typecheck / `vitest` work without a build step. The
 * generated file is excluded from prettier/eslint so committed == regenerated.
 *
 * Run manually:  pnpm tsx scripts/generate-skills-manifest.ts
 */

import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { scanSkills } from '../lib/agent/skill-fs'

const OUT = resolve(process.cwd(), 'lib/agent/skills.generated.ts')

const records = scanSkills('lib/agent/skills')

const file = `// AUTO-GENERATED by scripts/generate-skills-manifest.ts — DO NOT EDIT.
// Source: lib/agent/skills/. Regenerate: pnpm tsx scripts/generate-skills-manifest.ts
/* eslint-disable */
import type { GeneratedSkill } from './skill-schema'

export const SKILLS_MANIFEST: GeneratedSkill[] = ${JSON.stringify(records, null, 2)}
`

writeFileSync(OUT, file)
console.log(
  `[generate-skills-manifest] wrote ${OUT} — ${records.length} skill(s): ${records
    .map((r) => r.meta.name)
    .join(', ')}`
)
