'use client'

/**
 * Follow-up Question Chips
 * Renders clickable question pills generated by the suggest_followups tool.
 * Story 14.10: Dynamic follow-up suggestions
 */

import { MessageCircleQuestion } from 'lucide-react'
import type { FollowupQuestion } from '@/lib/hooks/use-followup-chips'

interface FollowupChipsProps {
  questions: FollowupQuestion[]
  onSelect: (_question: string) => void
}

export function FollowupChips({ questions, onSelect }: FollowupChipsProps) {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-2 duration-300 py-3 px-4">
      <p className="text-xs text-muted-foreground mb-2 flex items-center gap-1.5">
        <MessageCircleQuestion className="h-3 w-3" />
        Vill du gå djupare?
      </p>
      <div className="flex flex-wrap gap-2">
        {questions.map((q, i) => (
          <button
            key={i}
            onClick={() => onSelect(q.text)}
            className="text-left text-xs px-3 py-1.5 rounded-full border border-border bg-background hover:bg-muted hover:border-border/80 transition-colors text-muted-foreground hover:text-foreground"
          >
            {q.text}
          </button>
        ))}
      </div>
    </div>
  )
}
